# nginx proxy address - http://172.17.0.1:8074

name: homebox
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: ghcr.io/sysadminsmedia/homebox:latest
    pull_policy: always
    container_name: homebox-app
    restart: always
    logging: *default-logging
    networks:
      - homebox
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:8074:7745"
    environment:
      TZ: ${TZ:-America/New_York}
      HBOX_LOG_LEVEL: info
      HBOX_LOG_FORMAT: text
      HBOX_WEB_MAX_UPLOAD_SIZE: ${HBOX_MAX_UPLOAD_MB:-10}
      CONTAINER_NAME: homebox-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    volumes:
      - ./volumes/data/homebox:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:7745/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://homebox-app:7745'
      - 'cloudflare.hostname=homebox.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.homebox-app.entrypoints=http'
      - 'traefik.http.routers.homebox-app-secure.tls=true'
      - 'traefik.http.routers.homebox-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.homebox-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.homebox-app.middlewares=homebox-app-https-redirect'
      - 'traefik.http.routers.homebox-app-secure.entrypoints=https'
      - 'traefik.http.routers.homebox-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.homebox-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.homebox-app-secure.service=homebox-app'
      - 'traefik.http.services.homebox-app.loadbalancer.server.port=7745'

networks:
  homebox:
    name: homebox
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
