# nginx proxy address - http://172.17.0.1:8074

name: homebox
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: ghcr.io/sysadminsmedia/homebox:latest
    pull_policy: always
    container_name: homebox-app
    restart: always
    logging: *default-logging
    networks:
      - homebox
    ports:
      - "172.17.0.1:8074:7745"
    environment:
      TZ: ${TZ:-America/New_York}
      HBOX_LOG_LEVEL: info
      HBOX_LOG_FORMAT: text
      HBOX_WEB_MAX_UPLOAD_SIZE: ${HBOX_MAX_UPLOAD_MB:-10}
    volumes:
      - ./volumes/data/homebox:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:7745/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  homebox:
    name: homebox
    external: false
