# nginx proxy address - http://172.17.0.1:8074

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - homebox
    ports:
      - "8074:7745"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./volumes/config/homebox:/config
      - ./volumes/data/homebox:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7745"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  homebox:
    external: false
